version: "3"
services:
  mysql:
    container_name: slack_reaction_mysql
    build: ./docker/mysql
    ports:
    - "3306:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    tty:
      true
